name: hello-world

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-steps
        run: echo "Hello World!"
      - name: step 2
        run: pwd